### PR TITLE
Handle SQL UPDATE errors on long running jobs

### LINKED ISSUE #1263: File inventory job error
HoneyBadger reported an error when running the file inventory job in the background:

```
ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() could not receive data from server: 
Connection timed out SSL SYSCALL error: Connection timed out

[PROJECT_ROOT]/app/jobs/file_inventory_job.rb:39:in `perform' 
```

The error information points to `user_id 186` and `project_id 44`. 

https://tigerdata-qa.princeton.edu/projects/44

Matt confirmed that this is indeed the project that he reported during the check-in meeting today and that they job has not finished (it looks like it crashed.)

Honeybadger issue: https://app.honeybadger.io/projects/113559/faults/115546694 

The original error was dated `1/30/2025 at 9:48 AM -05:00` I think this was when Matt ran the job. There is another error reported at `1/30/2025 at 10:53 AM -05:00`. 

I manually re-ran the job right before `11:20 AM` and I don't see an error on Honeybadger and it looks like it generated the list. When I click "Download Complete List" it says it was generated 3 minutes ago.

Matt kick off the process again at `11:30 AM` to see if the error was a hiccup or a permissions issue. Almost 20 minutes later and Matt's job has not finished but there is no HoneyBadger error about it either. This is what the job looks like in the database:

```
#<FileInventoryRequest:0x00007f998ac64f78
 id: 13,
 user_id: 186,
 project_id: 44,
 job_id: "ecde7bff-e68d-440e-a44b-afcc2e4f4f86",
 completion_time: nil,
 state: "pending",
 type: "FileInventoryRequest",
 request_details: {"project_title"=>"Test 06-12-24"},
 created_at: Thu, 30 Jan 2025 16:30:04.976340000 UTC +00:00,
 updated_at: Thu, 30 Jan 2025 16:30:04.976340000 UTC +00:00>
```

### PR DESCRIPTION
**Pull request by hectorcorrea**
Closes #1263 

Thanks to @carolyncole for the pointer on what we did in PDC Describe for these kind of errors.

### CODE REVIEW

File: app/jobs/file_inventory_job.rb [hunk 1]
```diff
@@ -53,4 +50,15 @@ def filename_for_export
...
+
+    def update_inventory_request(user_id:, project:, job_id:, filename: )
+      inventory_request = FileInventoryRequest.find_by(user_id: user_id, project_id: project.id, job_id: job_id)
+      request_details = { output_file: filename, project_title: project.title, file_size: File.size(filename) }
+      inventory_request.update(state: UserRequest::COMPLETED, request_details: request_details,
+                                completion_time: Time.current.in_time_zone("America/New_York"))
+      inventory_request
+    rescue ActiveRecord::StatementInvalid
+      ActiveRecord::Base.connection_pool.release_connection
+      retry
```
Comment (hectorcorrea) [inline app/jobs/file_inventory_job.rb:62]: This is the important bit...handle this particular exception with a retry

**Review by carolyncole — APPROVED** [review]
Thanks @hectorcorrea
